hold:
  3:
    sendkey: 'ALT+SPACE'

swipe:
  3:
    left: 
      sendkey: 'LEFTALT+TAB'
    right: 
      sendkey: 'LEFTALT+LEFTSHIFT+TAB'
    up: 
      sendkey: 'LEFTCTRL+Q'
    down: 
      sendkey: 'LEFTALT+F4'
  4:
    left: 
      sendkey: 'LEFTALT+RIGHT'
    right: 
      sendkey: 'LEFTALT+LEFT'
    up: 
      sendkey: 'LEFTCTRL+TAB'
    down: 
      sendkey: 'LEFTCTRL+LEFTSHIFT+TAB'

pinch:
  2:
    in:
      sendkey: 'ZOOMIN'
    out:
      sendkey: 'ZOOMOUT'
  3:
    in:
      sendkey: 'LEFTCTRL+T'
    out:
      sendkey: 'LEFTCTRL+W'
  4:
    in:
      sendkey: 'LEFTMETA+D'
    out:
      sendkey: 'LEFTMETA+D'
threshold:
  swipe: 0.4
  pinch: 0.4
plugin: 
  inputs:
    libinput_command_input:
      enable-tap: true
      verbose: true
interval:
  swipe: 0.8
  pinch: 0.1
