--require('tabnine').setup({
--  accept_keymap = "<C-s>",
--  dismiss_keymap = "<C-]>",
--  debounce_ms = 800,
--  suggestion_color = { gui = "#808080", cterm = 244 },
--  exclude_filetypes = { "TelescopePrompt" },
--  log_file_path = nil, -- Set log file path if needed
--})
