on: 
  workflow_dispatch:
  push: 
    branches-ignore:
      - master
  pull_request:

name: Test Scripts
jobs:
  test:
    name: Test Scripts
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@master
    - run: |
        # Install pacapt
        sudo wget -O /usr/local/bin/pacapt https://github.com/icy/pacapt/raw/ng/pacapt
        sudo chmod 755 /usr/local/bin/pacapt
        echo y | sudo pacapt -Sy
        sudo ln -sf /usr/share/zoneinfo/UTC /etc/localtime
        echo y | sudo pacapt -Syyu tzdata
        echo y | sudo pacapt -Syyu curl sudo
        sh install.sh
        # curl -LsSf https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/install.sh | sh"
